events {
    worker_connections 1024;
}

stream {
    resolver 127.0.0.11 valid=10s;

    upstream radius_auth {
        server freeradius:1812;
    }

    upstream radius_acct {
        server freeradius:1813;
    }

    server {
        listen 1812 udp;
        proxy_pass radius_auth;
    }

    server {
        listen 1813 udp;
        proxy_pass radius_acct;
    }
}
