#!/bin/bash
# ══════════════════════════════════════════════════════════
# migrate_nginx_vars.sh — EXISTING-BOX migration
#
# Detects the CURRENT live nginx state (cert CN/IP, TLS files,
# htpasswd) and writes /etc/nms/nginx_vars.env so the new vars-
# driven pipeline adopts everything WITHOUT regenerating certs
# or touching the internal CA.
#
# Run once:  sudo bash infra/deploy/scripts/migrate_nginx_vars.sh
# ══════════════════════════════════════════════════════════
set -euo pipefail

VARS_FILE=/etc/nms/nginx_vars.env

if [ -f "$VARS_FILE" ]; then
    echo "[migrate] $VARS_FILE already exists — nothing to do."
    exit 0
fi

echo "[migrate] Detecting current nginx state…"

# 1) Primary IP: from the default route (most reliable)
NMS_HOST=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')
if [ -z "${NMS_HOST}" ]; then
    NMS_HOST=$(hostname -I | awk '{print $1}')
fi
if [ -z "${NMS_HOST}" ]; then
    echo "[migrate] ERROR: could not detect server IP — set NMS_HOST manually in $VARS_FILE"
    exit 1
fi

# 2) TLS mode: if a real cert exists → provided; else selfsigned
TLS_MODE="selfsigned"
CERT_FILE="/etc/nginx/ssl/nms_chain.crt"
KEY_FILE="/etc/nginx/ssl/nms.key"

if [ -f "$CERT_FILE" ]; then
    ISSUER=$(openssl x509 -in "$CERT_FILE" -noout -issuer 2>/dev/null | head -1)
    case "$ISSUER" in
        *Self-signed*|*localhost*)
            echo "[migrate] Existing cert is self-signed → TLS_MODE=selfsigned (will re-issue with SAN)"
            ;;
        *)
            echo "[migrate] Existing cert is CA-signed ($ISSUER) → preserving it"
            TLS_MODE="provided"
            ;;
    esac
fi

# 3) Write vars file (never touches certs/htpasswd — adoption only)
cat > "$VARS_FILE" <<EOF
# MY_NET NOC — Nginx customization (single source of truth)
# Generated by migrate_nginx_vars.sh on $(date '+%F %T')
# Edit values then apply: sudo bash infra/deploy/scripts/apply_nginx.sh

NMS_HOST=$NMS_HOST
TLS_MODE=$TLS_MODE
TLS_CERT_FILE=$CERT_FILE
TLS_KEY_FILE=$KEY_FILE
BASIC_AUTH_ENABLED=true
BASIC_AUTH_USER=admin
WAF_STRICT_UA=false
ACCESS_MODE=open
EOF

chmod 600 "$VARS_FILE"
echo ""
echo "✅ Migration complete: $VARS_FILE created"
echo "   Detected: NMS_HOST=$NMS_HOST, TLS_MODE=$TLS_MODE"
echo ""
echo "   Customize:   nano $VARS_FILE"
echo "   Apply:       sudo bash infra/deploy/scripts/apply_nginx.sh"
