apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    basicAuth: false
    isDefault: true
    jsonData:
      server: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: analytics
      username: grafana
    secureJsonData:
      password: 4992015a811d07ef46850ef7e928d7d10ca6d1296cabd5a8
    editable: true
