### FastNetMon Configuration
netflow = on
netflow_port = 2055

sflow = on
sflow_port = 6343

# Thresholds for ban
ban_for_pps = on
ban_for_bandwidth = on
ban_for_flows = off

ban_details_records_count = 500

threshold_pps = 20000
threshold_mbps = 1000
threshold_flows = 3500

enable_ban = on
ban_time = 1800

exim_path = /bin/false

# BGP integration (optional for auto-blackhole)
bgp = off
bgp_ip = 127.0.0.1
bgp_port = 179
bgp_peer_asn = 65001
bgp_local_asn = 65001
